name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Files using Rsync
        run: |
          rsync -avz --exclude='.git' -e "ssh" $GITHUB_WORKSPACE/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.PROJECT_PATH }}

      - name: Restart systemd service
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "sudo systemctl restart ${{ secrets.SERVICE_NAME }}"

  check_running_state:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Check service status
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "sudo systemctl status ${{ secrets.SERVICE_NAME }} --quiet || echo 'Service is not running or failed'"

      - name: Check if Service is Active
        run: |
          service_status=$(ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} "sudo systemctl is-active <service-name>")
          if [[ "$service_status" != "active" ]]; then
            echo "Service <service-name> is not running or failed."
            exit 1
          else
            echo "Service <service-name> is active."
          fi